SELECT N.HISTORY_ID, ROUND(((DATEDIFF(N.END_DATE, N.START_DATE) + 1) * N.DAILY_FEE) * ((100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100)) AS FEE 
FROM (
    SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, H.START_DATE, H.END_DATE,
           CASE 
               WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
               WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
               WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
               ELSE 0 
           END AS DURATION 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭' 
) N
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) D
ON N.DURATION = D.DURATION_TYPE
ORDER BY FEE DESC, N.HISTORY_ID DESC;
